version: "3.8"


services:
  nginx:
    build: ./nginx
    container_name: nginx
    links:
      - web
    depends_on:
      - web
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "80:80"
      - "443:443"

  web:
    container_name: api
    build: .
    command: >
      sh -c " python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py collectstatic --noinput &&
              gunicorn django_project.wsgi:application --bind 0.0.0.0:8000 --log-level debug --workers=15 --worker-class=gevent --worker-connections=500"
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
volumes:
  media_volume:
  static_volume: