# Generated by Django 4.1.3 on 2022-11-19 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='card',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_moderator',
        ),
        migrations.RemoveField(
            model_name='category',
            name='patronymic',
        ),
    ]
