# Generated by Django 4.1.3 on 2022-11-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='card',
            field=models.FileField(max_length=256, upload_to='media', verbose_name='Скидочная карта'),
        ),
    ]
