# Generated by Django 4.1.3 on 2022-11-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='indevirator',
            field=models.IntegerField(default=1, verbose_name='Индификатор'),
            preserve_default=False,
        ),
    ]
